export default {
  category: [
    {
      id: '1',
      categoryName: 'Burger',
    },
    {
      id: '2',
      categoryName: 'Noodles',
    },
    {
      id: '3',
      categoryName: 'sandwich',
    },
    {
      id: '4',
      categoryName: 'Pasta',
    },
    {
      id: '5',
      categoryName: 'Sea Food',
    },
    {
      id: '6',
      categoryName: 'pizza',
    },
    {
      id: '7',
      categoryName: 'desserts',
    },
    {
      id: '8',
      categoryName: 'beverages',
    },
  ],
  product: [
    {
      id: '1',
      categoryId: '1',
      productName: 'Crispy Fried Chicken Burger',
      images: require('./FdPhotos/1.png'),
      added: 0,
      rating: 3.5,
      Description:
        'This burger consists of a super crispy & flakey chicken patty on fresh lettuce, tomatoes and grilled onions with steak mayo.',
      price: '40',
    },
    {
      id: '2',
      categoryId: '1',
      productName: 'American smash burger',
      images: require('./FdPhotos/2.png'),
      added: 0,
      rating: 3.6,
      Description:
        'Smash Burgers are destined to be your favorite burgers! Crispy edges and a juicy middle,housed between two potato buns that soak up the juice, this is the ultimate bite!',
      price: '45',
    },
    {
      id: '3',
      categoryId: '1',
      productName: 'double chicken burger',
      images: require('./FdPhotos/3.png'),
      added: 0,
      rating: 3.7,
      Description:
        'Double crispy fried chicken topped with cheese, mayo, chilli garlic sauce and fresh lettuce with an option of extra cheese add-on',
      price: '40',
    },
    {
      id: '4',
      categoryId: '1',
      productName: 'Chipotle Black Bean Burger',
      images: require('./FdPhotos/4.png'),
      added: 0,
      rating: 3.8,
      Description:
        'These Chipotle Black Bean Burgers are the absolute best veggie burger. Filled with peppers, onions, adobe sauce, and spices, they’re a healthy vegetarian option the whole family will love.',
      price: '40',
    },
    {
      id: '5',
      categoryId: '1',
      productName: 'Cheese Loader',
      images: require('./FdPhotos/5.png'),
      added: 0,
      rating: 3.5,
      Description:
        'Whole Chicken Breast filled with cheese - onions - jalapenos - iceberg - burger sauce.',
      price: '42',
    },
    {
      id: '6',
      categoryId: '1',
      productName: 'BBQ burger',
      images: require('./FdPhotos/6.png'),
      added: 0,
      rating: 3.9,
      Description:
        "It tastes as good as it looks! Grilled chicken fillet topped with tomatoes, lettuce, caramelised onions, Lab's special smoked and BBQ sauce in soft-n-fresh 'Potato Bun' to enhance the flavour of each bite.",
      price: '41',
    },
    {
      id: '7',
      categoryId: '1',
      productName: 'Zinger burger',
      images: require('./FdPhotos/7.png'),
      added: 0,
      rating: 4.0,
      Description:
        'Extremely crispy, twice-dredged chicken fillets slathered with a special burger sauce - double cheese (mozzarella & american) - iceberg - Mayonnaise',
      price: '40',
    },
    {
      id: '8',
      categoryId: '2',
      productName: 'chicken singapore noodles',
      images: require('./FdPhotos/8.png'),
      added: 0,
      rating: 4.1,
      Description:
        'Delicious Syn Free Chicken Singapore Noodles – a curry flavour noodle dish that will become a regular on your meal plans.',
      price: '38',
    },
    {
      id: '9',
      categoryId: '2',
      productName: 'hoisin chicken with noodles',
      images: require('./FdPhotos/9.png'),
      added: 0,
      rating: 4.2,
      Description:
        'Hoisin Chicken with Noodles – tender strips of chicken breast and vegetables with egg noodles all coated in a delicious Hoisin Sauce',
      price: '40',
    },
    {
      id: '10',
      categoryId: '2',
      productName: 'Chili Beef Noodles',
      images: require('./FdPhotos/10.png'),
      added: 0,
      rating: 4.3,
      Description:
        'A ridiculously tasty vegan version of the popular Asian dish with a spicy kick.Crispy Chilli Beef! ',
      price: '40',
    },
    {
      id: '11',
      categoryId: '2',
      productName: 'Peanut chicken noodles',
      images: require('./FdPhotos/11.png'),
      added: 0,
      rating: 4.4,
      Description:
        'A delicious simple noodle stir fry with chicken, vegetables and a peanut sauce.',
      price: '35',
    },
    {
      id: '12',
      categoryId: '2',
      productName: 'hakka noodles',
      images: require('./FdPhotos/12.png'),
      added: 0,
      rating: 3.5,
      Description:
        'A popular Indian Chinese dish made by stir frying hakka noodles with veggies, sauces and garlic.',
      price: '35',
    },
    {
      id: '13',
      categoryId: '2',
      productName: 'Spicy Vegetable Noodles',
      images: require('./FdPhotos/13.png'),
      added: 0,
      rating: 4.5,
      Description:
        'Spicy vegetable noodles is a one pot meal that is spicy and delicious with the goodness of fresh spring vegetables',
      price: '30',
    },
    {
      id: '14',
      categoryId: '2',
      productName: 'Ginger Chicken noodles',
      images: require('./FdPhotos/14.png'),
      added: 0,
      rating: 4.6,
      Description:
        'Soy and ginger chicken with Oriental-style vegetables and noodles of egg noodles',
      price: '35',
    },
    {
      id: '15',
      categoryId: '3',
      productName: 'Veg Toast Sandwich',
      images: require('./FdPhotos/15.png'),
      added: 0,
      rating: 4.7,
      Description:
        'This sandwich is very nutritious as well as spicy and tangy.stuffed with veggies like tomatoes, cucumber, capsicum, and onions.',
      price: '30',
    },
    {
      id: '16',
      categoryId: '3',
      productName: 'Crispy Fish Sandwich',
      images: require('./FdPhotos/16.png'),
      added: 0,
      rating: 4.8,
      Description:
        'Crispy fried white flounder fillets enveloped in two thick slices of white bread, piled high with iceberg lettuce, pickles, onions, and of course, potato chips.',
      price: '40',
    },
    {
      id: '17',
      categoryId: '3',
      productName: 'Classic club sandwich',
      images: require('./FdPhotos/17.png'),
      added: 0,
      rating: 4.9,
      Description:
        'Classic Club Sandwich with Grilled Chicken, Turkey Becon, Omelette, Tomatoes, Orange Cheddar Cheese, Cucumbers with honey.',
      price: '45',
    },
    {
      id: '18',
      categoryId: '3',
      productName: 'Chicken Croissant Sandwich',
      images: require('./FdPhotos/18.png'),
      added: 0,
      rating: 5.0,
      Description:
        'Flaky Croissant with Grilled Chicken, Cheddar, Bell Peppers, Chopped Iceberg, Green Chillies and a Honey Mustard Mayo',
      price: '40',
    },
    {
      id: '19',
      categoryId: '3',
      productName: 'The Smoke Salmon Club',
      images: require('./FdPhotos/19.png'),
      added: 0,
      rating: 4.9,
      Description:
        'Norwegian Smoked Salmon Club Sandwich with Hard Boiled Egg, Cucumbers and a Lemon Infused Homemade Mayo served with Fries & Green Salad',
      price: '45',
    },
    {
      id: '20',
      categoryId: '3',
      productName: 'Ranch Chicken Sandwich',
      images: require('./FdPhotos/20.png'),
      added: 0,
      rating: 4.8,
      Description:
        'Delicious grilled chicken thinly sliced, topped with our home-made spicy red sauce served in a cheese and garlic bread, with fries and dip on the side.',
      price: '45',
    },
    {
      id: '21',
      categoryId: '3',
      productName: 'Roasted Beef Sandwich',
      images: require('./FdPhotos/21.png'),
      added: 0,
      rating: 4.7,
      Description:
        'A special treat for beef lovers, thin roasted beef slices topped with our special sauce encased between focaccia bread, served with fries and our home-made dip.',
      price: '50',
    },
    {
      id: '22',
      categoryId: '4',
      productName: 'Penne Arrabiata Pasta',
      images: require('./FdPhotos/22.png'),
      added: 0,
      rating: 4.6,
      Description:
        'Spicy. Penne pasta tossed with hot tomato sauce, mushrooms, black olives & topped with parmesan cheese. Served with garlic bread.',
      price: '45',
    },
    {
      id: '23',
      categoryId: '4',
      productName: 'Chicken Caesar Pasta',
      images: require('./FdPhotos/23.png'),
      added: 0,
      rating: 4.5,
      Description:
        'Spicy. Penne pasta tossed with spicy creamy sauce, black olives, mushrooms & jalapeno. Served with garlic bread.',
      price: '50',
    },
    {
      id: '24',
      categoryId: '4',
      productName: 'Parmesan Chicken Pasta',
      images: require('./FdPhotos/24.png'),
      added: 0,
      rating: 4.4,
      Description:
        'Golden Fried chicken bread over penne pasta tossed in parmesan cream sauce & topped with marinara & cheese. Served with garlic bread.',
      price: '50',
    },
    {
      id: '25',
      categoryId: '4',
      productName: 'Fettuccine Alfredo Pasta',
      images: require('./FdPhotos/25.png'),
      added: 0,
      rating: 4.3,
      Description:
        'Fettuccine alfredo pasta tossed with alfredo creamy sauce topped with grilled chicken. Served with garlic bread.',
      price: '55',
    },
    {
      id: '26',
      categoryId: '5',
      productName: 'Fish & Chips',
      images: require('./FdPhotos/26.png'),
      added: 0,
      rating: 4.2,
      Description:
        'Strips of fish breaded and fried golden brown, served with tartar sauce and french fries.',
      price: '55',
    },
    {
      id: '27',
      categoryId: '5',
      productName: 'Grilled Jumbo Prawns',
      images: require('./FdPhotos/27.png'),
      added: 0,
      rating: 4.1,
      Description:
        'umbo prawns grilled and basted with spicy sauce, served with lemon aioli sauce, saffron rice and sauteed vegetables.',
      price: '55',
    },
    {
      id: '28',
      categoryId: '5',
      productName: 'Grilled Tandoori Fish',
      images: require('./FdPhotos/28.png'),
      added: 0,
      rating: 4.0,
      Description:
        'Fillets of mackerel marinated in homemade spices, pan fried served with spanish rice and chef vegetables.',
      price: '55',
    },
    {
      id: '29',
      categoryId: '5',
      productName: 'Hot N Spicy Prawns',
      images: require('./FdPhotos/29.png'),
      added: 0,
      rating: 3.9,
      Description:
        'Diced prawns sauteed in garlic butter, tossed in a spicy sambal sauce, served with rice pilaf and chief vegetables.',
      price: '60',
    },
    {
      id: '30',
      categoryId: '5',
      productName: 'Parmessan Fish',
      images: require('./FdPhotos/30.png'),
      added: 0,
      rating: 3.8,
      Description:
        'Fillet of red snapper, pan fried, served with whole grain mustard sauce on a mound of mash potatoes along with chef vegetables.',
      price: '60',
    },
    {
      id: '31',
      categoryId: '5',
      productName: 'Red Snapped With Lemon Butter Sauce',
      images: require('./FdPhotos/31.png'),
      added: 0,
      rating: 3.7,
      Description:
        'Grilled fillet of red snapper served with lemon butter sauce on a bed of rice pilaf and sauteed vegetables.',
      price: '60',
    },
    {
      id: '32',
      categoryId: '6',
      productName: 'Chicken Tikka pizza',
      images: require('./FdPhotos/32.png'),
      added: 0,
      rating: 3.6,
      Description:
        'Traditional Tikka flavored chunks perfectly set with American style hand tossed crust to bring the best of both worlds.',
      price: '55',
    },
    {
      id: '33',
      categoryId: '6',
      productName: 'Chicken Fajita pizza',
      images: require('./FdPhotos/33.png'),
      added: 0,
      rating: 3.5,
      Description:
        'The Chicken Fajita topping is a divine blend of fresh oregano and paprika for the right flavors to hit your spice-buds.',
      price: '55',
    },
    {
      id: '34',
      categoryId: '6',
      productName: 'Creamy Chicken Delight pizza',
      images: require('./FdPhotos/34.png'),
      added: 0,
      rating: 3.4,
      Description:
        'A delightful mix of chicken fajita chunks, onions, green chillis, and tomatoes atop our homemade creamy garlic sauce.',
      price: '60',
    },
    {
      id: '35',
      categoryId: '6',
      productName: 'Hot Chicken pizza',
      images: require('./FdPhotos/35.png'),
      added: 0,
      rating: 3.3,
      Description:
        'A combination of diced chicken mughlai, onions and jalepenos spread over our signature fiery sauce and drizzled with our secret creamy dressing.',
      price: '55',
    },
    {
      id: '36',
      categoryId: '6',
      productName: 'Peri Tikka Fusion pizza',
      images: require('./FdPhotos/36.png'),
      added: 0,
      rating: 3.2,
      Description:
        'A twist to the classic pizza, the Peri Tikka Fusion is made with the original Peri-Peri sauce that is topped with marinated pieces of chicken tikka, onions, and green pepper',
      price: '60',
    },
    {
      id: '37',
      categoryId: '6',
      productName: 'Supreme Beef pizza',
      images: require('./FdPhotos/37.png'),
      added: 0,
      rating: 3.1,
      Description:
        "A beef lover's dream, Basically Beef is a combination of ground beef, tomatoes, onions and Jalapenos.",
      price: '60',
    },
    {
      id: '38',
      categoryId: '6',
      productName: 'BBQ pizza',
      images: require('./FdPhotos/38.png'),
      added: 0,
      rating: 3.0,
      Description:
        'Smoked chicken, capsicum, onions and black olives, sweet and smoky BBQ sauce.',
      price: '60',
    },
    {
      id: '39',
      categoryId: '7',
      productName: 'Chocolate Malt Waffles',
      images: require('./FdPhotos/39.png'),
      added: 0,
      rating: 2.9,
      Description:
        'Chocolate waffles, perfect for breakfast, or as a decadent dessert with ice cream and fudge sauce.',
      price: '30',
    },
    {
      id: '40',
      categoryId: '7',
      productName: 'Molten Chocolate Lava Cake',
      images: require('./FdPhotos/40.png'),
      added: 0,
      rating: 2.8,
      Description:
        "Molten Chocolate Lava Cake is a rich, fudgy little flourless chocolate cake with a soft, gooey centre. Served warm with a scoop of vanilla ice cream, it's simply divine!",
      price: '35',
    },
    {
      id: '41',
      categoryId: '7',
      productName: 'creme brulee',
      images: require('./FdPhotos/41.png'),
      added: 0,
      rating: 2.7,
      Description:
        'With a rich, creamy vanilla custard and crunchy, caramelised topping, our crème brûlée makes the ultimate indulgent dessert',
      price: '35',
    },
    {
      id: '42',
      categoryId: '7',
      productName: 'Mocha and Salted Caramel Sundae',
      images: require('./FdPhotos/42.png'),
      added: 0,
      rating: 2.6,
      Description:
        'The combination of coffee and chocolate with salted caramel brings out a multitude of flavours that really compliments the sweetness of the ice cream. Sprinkling chocolate macaroons in too adds an extra layer of crunch that makes this sundae feel super special.',
      price: '30',
    },
    {
      id: '43',
      categoryId: '7',
      productName: 'Layered Ice Cream Cookie Cake',
      images: require('./FdPhotos/43.png'),
      added: 0,
      rating: 2.5,
      Description:
        "A decadent layered 'cake' made with ice cream and cookies is a great way to celebrate.",
      price: '20',
    },
    {
      id: '44',
      categoryId: '7',
      productName: 'Fudgy Triple Chocolate',
      images: require('./FdPhotos/44.png'),
      added: 0,
      rating: 3.5,
      Description:
        'These fudgy brownies are made with 3 types of chocolate to give them a rich and decadent chocolate flavor. They’re thick, dense, not the least bit cakey, and taste delicious served plain or with a scoop of vanilla ice cream.',
      price: '20',
    },
    {
      id: '45',
      categoryId: '8',
      productName: 'Vanilla shake',
      images: require('./FdPhotos/45.png'),
      added: 0,
      rating: 3.5,
      Description:
        'This icy classic vanilla shake tastes amazing and will keep you cool .With whipped cream, sugar free chocolate syrup.',
      price: '25',
    },
    {
      id: '46',
      categoryId: '8',
      productName: 'Pina Colada',
      images: require('./FdPhotos/46.png'),
      added: 0,
      rating: 3.5,
      Description:
        'Made with fresh pineapple, coconut and Greek yogurt, this pina colada smoothie is a fantastic healthy snack or breakfast idea!',
      price: '25',
    },
    {
      id: '47',
      categoryId: '8',
      productName: 'Mint lemonade',
      images: require('./FdPhotos/47.png'),
      added: 0,
      rating: 3.5,
      Description:
        'This Limonana (Middle Eastern Frozen Mint Lemonade) is sweet, tart, and refreshing, and perfect for cooling down with on a hot day!',
      price: '20',
    },
    {
      id: '48',
      categoryId: '8',
      productName: 'Brownie Milkshake',
      images: require('./FdPhotos/48.png'),
      added: 0,
      rating: 3.5,
      Description:
        'This Brownie Milkshake is a super decadent treat every chocolate lover should taste at least once! Loaded with brownie chunks and decorated with ganache, this milkshake is packed with delicious chocolate flavour. ',
      price: '35',
    },
    {
      id: '49',
      categoryId: '8',
      productName: 'strawberry shake',
      images: require('./FdPhotos/49.png'),
      added: 0,
      rating: 3.5,
      Description:
        'This milkshake is made with strawberry ice cream and fresh strawberries, healthy and yummy!',
      price: '30',
    },
    {
      id: '50',
      categoryId: '8',
      productName: 'blueberry shake',
      images: require('./FdPhotos/50.png'),
      added: 0,
      rating: 3.5,
      Description:
        'This creamy and refreshing blueberry smoothie is made with juice, yogurt, frozen blueberries and banana, all blended together into a frosty drink.',
      price: '30',
    },
  ],
};
